### PR TITLE
fixed grammatical error!

### PR DESCRIPTION
**Pull request by normanchenn**
@PeteMango

### CODE REVIEW

**Comment by petemango** [comment]
Please make your pull request description more informative and helpful! Thanks.

**Comment by rrogerc** [comment]
Hi guys, can we be friends?

**Comment by normanchenn** [comment]
@PeteMango I wanted to fix a grammatical error I found while perusing your README file. As an avid fan of yours, I wanted you to have the most accurate language possible in your README. In this case, I changed what was formerly `Formely` to `Formerly`, as that is the correct way to spell "Formerly".

**Comment by petemango** [comment]
Awesome! Thank you so much for the descriptive pull request. I'm sure future developers of this repository will look back and thank you for your superb contributions.

**Pull request merged**
